---
  # roles/launch-configuration/tasks/main.yml

  - name: find the ami
    ec2_ami_find:
        region: "{{ region }}"
        name: "{{ new_ami_name }}"
    register: ami_find

  - name: Create Launch Configuration
    ec2_lc:
      region: "{{ region }}"
      name: "my-webapp-lc"
      image_id: "{{ ami_find.results[0].ami_id }}"
      key_name: "{{ keypair }}"
      instance_type: "{{ instance_type }}"
      security_groups: "{{ security_groups }}"
      instance_monitoring: yes
